label: DT02\n192.168.88.52
label.near: top-center
shape: rectangle
firecracker: {
    label: Firecracker
    label.near: top-center
    shape: rectangle

    vm00: @vm00
    vm03: @vm03
    vm04: @vm04
}
