label: DT05\n192.168.88.55
label.near: top-center
shape: rectangle
docker: {
    label: Docker
    label.near: top-center
    doco-cd: {
        label: Doco CD
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }
    dozzle: {
        label: Dozzle
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dozzle.svg
    }
}