label: DT06\n192.168.88.56
label.near: top-center
shape: rectangle
k8s: {
    label: Kubernetes
    label.near: top-center
    argo: {
        label: Argo CD
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/argo-cd.svg
    }
    homer: {
        label: Homer
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/homer.svg
    }
}


