label: DT06\n192.168.88.56
label.near: top-center
shape: rectangle
k8s: {
    label: Kubernetes
    label.near: top-center
    grid-columns: 5
    argo: {
        label: Argo CD
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/argo-cd.svg
    }
    cnpg: {
        label: CloudNativePG
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fpostgresql.svg
    }
    dashboard: {
        label: Dashboard
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/azure%2F_Companies%2FKubernetes.svg
    }
    extsec: {
        label: External Secrets
        label.near: outside-bottom-center
        shape: image
        icon: https://external-secrets.io/latest/pictures/eso-round-logo.svg
    }
    grafana: {
        label: Grafana
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg
    }
    homer: {
        label: Homer
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/homer.svg
    }
    ingress: {
        label: Ingess-Nginx
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nginx.svg
    }
    jellyfin: {
        label: Jellyfin
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
    }
    keda: {
        label: KEDA
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/keda.svg
    }
    loki: {
        label: Loki
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/loki.svg
    }
    magazines: {
        label: Magazines
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/essentials%2F257-file.svg
    }
    maria: {
        label: MariaDB Operator
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/mariadb.svg
    }
    netbox: {
        label: Netbox
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/netbox.svg
    }
    openspeedtest: {
        label: OpenSpeedTest
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/openspeedtest.svg
    }
    pgadmin: {
        label: pgAdmin
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pgadmin.svg
    }
    phpmyadmin: {
        label: phpMyAdmin
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/phpmyadmin.svg
    }
    rediscdr: {
        label: Redis Commander
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fredis.svg
    }
    rediscdr: {
        label: Redis Commander
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fredis.svg
    }
    redisop: {
        label: Redis Operator
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fredis.svg
    }
    registry: {
        label: Registry
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }
    snake: {
        label: Snake
        label.near: outside-bottom-center
        shape: image
        icon: https://icons.terrastruct.com/tech%2F048-gamepad.svg
    }
    uptimekuma: {
        label: Uptime Kuma
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/uptime-kuma.svg
    }
    vscode: {
        label: Visual Studio Code
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/code.svg
    }
    wyl: {
        label: WatchYourLAN
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/watchyourlan.png
    }
    wiki: {
        label: Wiki
        label.near: outside-bottom-center
        shape: image
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/mkdocs.svg
    }
}   


