label: DT07\n192.168.88.57
label.near: top-center
shape: rectangle
netbird: {
    label: Netbird
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/netbird.svg
}


