label: DT09\n192.168.88.59
label.near: top-center
shape: rectangle
k8s: {
    label: Kubernetes
    label.near: top-center
    cluster: {
        label: Cluster Services
        label.near: top-center
        grid-columns: 2
        certmanager: {
            label: Cert-Manager
            label.near: outside-bottom-center
            shape: image
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cert-manager.svg
        }
        extsec: {
            label: External Secrets
            label.near: outside-bottom-center
            shape: image
            icon: https://external-secrets.io/latest/pictures/eso-round-logo.svg
        }
        flux: {
            label: FluxCD
            label.near: outside-bottom-center
            shape: image
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/flux-cd.svg
        }
        longhorn: {
            label: Longhorn
            label.near: outside-bottom-center
            shape: image
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/longhorn.svg
        }
        metallb: {
            label: MetalLB
            label.near: outside-bottom-center
            shape: image
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/metallb.svg
        }
        ngf: {
            label: NGINX Gateway Fabric
            label.near: outside-bottom-center
            shape: image
            icon: https://docs.nginx.com/images/icons/NGINX-Gateway-Fabric-product-icon.svg
        }
    }
    apps: {
        label: Apps
        label.near: top-center
        headlamp: {
            label: Headlamp
            label.near: outside-bottom-center
            shape: image
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/headlamp.svg
        }
    }
}


