label: MD03\n192.168.88.83
label.near: top-center
shape: rectangle
jellyfin: {
    label: Jellyfin
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
}


