label: NS01\n192.168.88.31
label.near: top-center
shape: rectangle
nas: {
    label: NAS
    label.near: outside-bottom-center
    shape: image
    icon: https://icons.terrastruct.com/tech%2F069-hard-drive.svg
}


