label: NS02\n192.168.88.32
label.near: top-center
shape: rectangle
backup: {
    label: Backups (MinIO)
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/minio.svg
}


