label: RP04\n192.168.88.24
label.near: top-center
shape: rectangle
pihole: {
    label: Pi-Hole
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pi-hole.svg
}


