near: bottom-center

ado: {
    label: Azure DevOps
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/azure-devops.svg
}
akeyless: {
    label: Akeyless
    label.near: outside-bottom-center
    shape: image
    icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1stDIOP4mvG62H23V2IS0OCzEGUFoWjYLYA&s
}
bitwarden: {
    label: Bitwarden
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/bitwarden.svg
}
github: {
    label: Github
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/github.svg
}
neon: {
    label: Neon
    label.near: outside-bottom-center
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/neon-tech.svg
}
pcloud: {
    label: pCloud
    label.near: outside-bottom-center
    shape: image
    icon: ../../icons/pcloud-svgrepo-com.svg
}