label: VM99\n192.168.90.99
label.near: top-center
shape: rectangle
ubuntu: {
    label: Xen Orchestra
    shape: image
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/xen-orchestra.svg
}